sonar.projectKey=Gr84H-NewsRadar_NewsRadar
sonar.organization=gr84h-newsradar
sonar.projectName=NewsRadar

sonar.sources=newsradar_api/app
sonar.tests=newsradar_api/tests
sonar.exclusions=**/__pycache__/**,**/*.pyc

sonar.python.version=3.11
sonar.python.coverage.reportPaths=newsradar_api/coverage.xml

sonar.sourceEncoding=UTF-8
